# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: RSpec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.2, 3.3, 3.4, 4.0]
        rails-version: ["~> 7.1.0", "~> 7.2.0", "~> 8.0.0", "~> 8.1.0"]
    steps:
      # Checkout repo
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
        env:
          RAILS_VERSION: ${{ matrix.rails-version }}
      - name: Bundle install
        run: |
          bundle update rails
          bundle install --jobs 4 --retry 3
        env:
          RAILS_VERSION: ${{ matrix.rails-version }}

      - name: Setup Database
        working-directory: spec/dummy
        run: bin/rails db:prepare RAILS_ENV=test
        env:
          RAILS_VERSION: ${{ matrix.rails-version }}

      - name: Run RSpec
        run: bundle exec rake
        env:
          RAILS_VERSION: ${{ matrix.rails-version }}
